#importamos la imagen base con python
FROM python:3.12-slim 

#creamos carpeta de trabajo del contenedor
WORKDIR /app

#copiamos los requerimientos del servidor
COPY requirements.txt .

#Ejecutamoslos requerieminetos 
RUN pip install --no-cache-dir -r requirements.txt

#copiar el codigo de la API
COPY ./app ./app

#Exponer el puerto
EXPOSE 8010

#Comando de ejecucion FASTAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8010","--reload"]

#sirve oara hacer la interaccion entre uno o mas contenedoreas 
# docker-compose up --build